### ISSUE TITLE
Gateway - Coder workspace stays in the Connecting state forever after workspace update

### ISSUE THREAD

**Issue by iuliiasobolevska** [coder/jetbrains-coder#327]
**Steps to reproduce:**
1. Let's assume there is a workspace in a Running state.
2. Open JetBrains Gateway and select "Connect to Coder". In the "Coder Workspaces" window you should see that workspace in the Running state. No need to connect to any.
3. Now let's say I see
```
An update is available for your workspace
Uploaded from the CLI
```
message in the browser workspaces view and I click on the "Update" button.
![Screenshot 2023-11-13 at 1 26 31 PM](https://github.com/coder/jetbrains-coder/assets/2178468/ad5e79d9-3c29-42cf-8ea6-3cb1b4c71d91)

4. Workspace is updated and shows as "Running" in the browser but stays forever in the "Connecting" state in the Gateway - Coder Workspaces UI:
![Screenshot 2023-11-09 at 4 09 51 PM](https://github.com/coder/jetbrains-coder/assets/2178468/54a100d8-3de5-4df7-ab73-f40d9c489f09)

Restarting the workspace and the Gateway (sometimes a couple of times) resolves the issue.

**Comment by iuliiasobolevska** [comment]
We suspect the issue is on our side so closing for now.

**Comment by code-asher** [comment]
Just in case it is helpful, the `Connecting` state here means that the workspace is running but we are waiting to connect to the agent.  I think the dashboard just shows `Running` if the workspace is running and you have to click in or look below to see the status of the agent.

The help tooltip only says `The agent is connecting` so possibly we should change that to `The workspace is running and the agent is connecting` because I think the existing text it is not entirely clear.

**Comment by wfclark5** [comment]
@iuliiasobolevska Hello! I am running into a similar issue and out of curiosity was wondering if there are any other issues tracking this work? If there are no open issues, insight into known problems on the deployment or plugin side that could be changed to remediate this issue would be awesome! We are currently making sure that the Gateway application and the plugin are up to date. Any insight at all would be greatly appreciated! 🚀
